### ISSUE TITLE
Offer only class specific functions?

### ISSUE THREAD

**Issue by Benik3** [Serpen/VBS-VSCode#35] opened 2020-10-13 10:48 UTC
Now intellisense offers functions/Subs/Property from all classes even that the selected class doesn't support it:  
![obrazek](https://user-images.githubusercontent.com/4532647/95851331-5f2a0200-0d52-11eb-9bbe-6a73c7679dc4.png)

**Comment by Serpen** [comment] 2020-10-13 12:59
Yes, this is currently the way it works. Duplicate of #18.
Since VBS has now typesystem, VBS can **only guarantee at runtime** to know which type a variable is.
So it es pure guessing, so I decided to offer everything instead of nothing.

If I get the pseudo typesystem running, this can change.

More Worse: In your Screenshot you try to access instance members as instance members. VBS has no shared or static keyword. That code would never work.

**Closed by Serpen** 2020-10-13 12:59 UTC

**Comment by Benik3** [comment] 2020-10-13 17:18
> More Worse: In your Screenshot you try to access instance members as instance members. VBS has no shared or static keyword. That code would never work.

That's true. The reason is, that we use scripts in SW, which has already created these objects, but the inbuilt editor is very simple.
So I wanted to try to write the scripts in e.g. VSCode with IntelliSense and then import them back. The scripts will never work outside of the SW anyway.

I forgot that in VBscript you can change even the object type as you want :/
So only for evident object it would be applicable (like when you have Set dict = CreateObject("Scripting.Dictionary")), otherwise I assume it wiould be pretty hard to track it the Intellisense.
